### ISSUE TITLE
Improve makefile

### ISSUE THREAD

**Issue by FernandezEnrique** [LeviDooku/Data-Base-Using-Binary-Array#1]
Hello!!
I liked your project and I have been checking it and I realized that you may can improve your makefile running it once instead of twice.

Instead of 
`makefile -f makefile.mak Directories`

Just run `makefile`, change its name to `Makefile` and in the first instruction add in dependences `Directories` so it will run together with just one order. 

`all : Directories $(BIN)/Basic_Data_Base`

**Comment by LeviDooku** [comment]
Hi!
Thank u very much for your recommendation. I've just applied it :)
